name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Zig
      uses: mlugg/setup-zig@v2
      with:
        version: 0.14.1
        mirror: 'https://ziglang.org/download'
    
    - name: Run tests
      run: zig build test

  build:
    name: Build
    needs: test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-linux
            artifact_name: case-switcher
          - os: windows-latest
            target: x86_64-windows
            artifact_name: case-switcher.exe
          - os: macos-latest
            target: x86_64-macos
            artifact_name: case-switcher
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Zig
      uses: mlugg/setup-zig@v2
      with:
        version: 0.14.1
        mirror: 'https://ziglang.org/download'
    
    - name: Build for ${{ matrix.target }}
      run: zig build --release=fast
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.target }}
        path: zig-out/bin/${{ matrix.artifact_name }}