name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Release
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-linux
            artifact_name: case-switcher
            asset_name: case-switcher-linux-x86_64
          - os: windows-latest
            target: x86_64-windows
            artifact_name: case-switcher.exe
            asset_name: case-switcher-windows-x86_64.exe
          - os: macos-latest
            target: x86_64-macos
            artifact_name: case-switcher
            asset_name: case-switcher-macos-x86_64
          - os: macos-latest
            target: aarch64-macos
            artifact_name: case-switcher
            asset_name: case-switcher-macos-aarch64
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Zig
      uses: mlugg/setup-zig@v1
      with:
        version: 0.14.1
    
    - name: Build for ${{ matrix.target }}
      run: zig build --release=fast -Dtarget=${{ matrix.target }}
    
    - name: Compress binary (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        cd zig-out/bin
        tar -czf ../../${{ matrix.asset_name }}.tar.gz ${{ matrix.artifact_name }}
    
    - name: Compress binary (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd zig-out/bin
        7z a ../../${{ matrix.asset_name }}.zip ${{ matrix.artifact_name }}
    
    - name: Upload Release Asset (Unix)
      if: matrix.os != 'windows-latest'
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ matrix.asset_name }}.tar.gz
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload Release Asset (Windows)
      if: matrix.os == 'windows-latest'
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ matrix.asset_name }}.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}